// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfW7jMPNl7eUk7nR_CKRDMgAFgurme7wo',
    appId: '1:847505776831:web:c203c0015703b85b78a60a',
    messagingSenderId: '847505776831',
    projectId: 'pedi-6ba5b',
    authDomain: 'pedi-6ba5b.firebaseapp.com',
    storageBucket: 'pedi-6ba5b.firebasestorage.app',
    measurementId: 'G-5KM87ZY12T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpO3ArpVdriUrkye57-fN4z0NJ8ncznIc',
    appId: '1:847505776831:android:9d167ecea7291f9578a60a',
    messagingSenderId: '847505776831',
    projectId: 'pedi-6ba5b',
    storageBucket: 'pedi-6ba5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo0CT30IM_Ic0h8byzmsFN8fV4CAZiQnM',
    appId: '1:847505776831:ios:43ce567e32787bbc78a60a',
    messagingSenderId: '847505776831',
    projectId: 'pedi-6ba5b',
    storageBucket: 'pedi-6ba5b.firebasestorage.app',
    iosBundleId: 'com.pedi.app.pedi',
  );
}
